<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>disable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<PlatformTarget>x64</PlatformTarget>
	</PropertyGroup>
	<ItemGroup>
	  <Content Remove="..\x64\Debug\CudaRuntime.dll" />
	</ItemGroup>
	<ItemGroup>
		<Content Include="..\x64\$(Configuration)\CudaRuntime.dll">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<Link>%(Filename)%(Extension)</Link>
			<Visible>false</Visible>
		</Content>
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\CudaRuntime\CudaRuntime.vcxproj">
	    <ReferenceOutputAssembly>False</ReferenceOutputAssembly>
	    <Private>True</Private>
	  </ProjectReference>
	</ItemGroup>
</Project>
